x-backend-base: &backend-base
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - ${ENV_FILE:-.env.local}
  environment:
    DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://bullbear:bullbear@db:5432/bullbear}
    REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    BULLBEAR_DEFAULT_USER: ${BULLBEAR_DEFAULT_USER:-test@bullbear.ai}
    BULLBEAR_DEFAULT_PASSWORD: ${BULLBEAR_DEFAULT_PASSWORD:-Test1234!}
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

x-frontend-base: &frontend-base
  build:
    context: ./frontend
    dockerfile: Dockerfile
  env_file:
    - ${ENV_FILE:-.env.local}

services:
  db:
    container_name: bullbear-db
    profiles: ["default", "staging"]
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bullbear}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bullbear}
      POSTGRES_DB: ${POSTGRES_DB:-bullbear}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bullbear}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: bullbear-redis
    profiles: ["default", "staging"]
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: bullbear-backend
    <<: *backend-base
    profiles: ["default"]
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  backend-staging:
    container_name: bullbear-backend-staging
    <<: *backend-base
    profiles: ["staging"]
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    container_name: bullbear-frontend
    <<: *frontend-base
    profiles: ["default"]
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:8000}
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend-staging:
    container_name: bullbear-frontend-staging
    <<: *frontend-base
    profiles: ["staging"]
    command: npm start
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend-staging:8000}
    depends_on:
      backend-staging:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  postgres_data:
