version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bullbear_api
    environment:
      BULLBEAR_ENV: "development"
      BULLBEAR_DB_URL: "sqlite:////app/data/app.db"
      BULLBEAR_RATE_LIMIT_BACKEND: "memory"
      BULLBEAR_MIGRATE_ON_START: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - appdata:/app/data
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  appdata:
