version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: bullbearbroker-backend:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://bullbear:bullbear@postgres:5432/bullbear
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bullbear
      POSTGRES_USER: bullbear
      POSTGRES_PASSWORD: bullbear
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
