version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: '${NEXT_PUBLIC_API_BASE_URL:-http://backend:8000}'
    depends_on:
      - backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
