version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: bullbearbroker-backend:latest
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/api/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  alert-worker:
    image: bullbearbroker-backend:latest
    command: python -m services.alert_service
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - backend

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  frontend:
    image: nginx:alpine
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
