name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install pnpm
        run: corepack enable

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Run frontend tests
        run: pnpm test:frontend

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install diff-cover
          corepack enable

      - name: Run backend tests with coverage
        run: pnpm test:backend:cov

      - name: Generate coverage XML
        run: python -m coverage xml -i

      - name: Diff coverage (informativo)
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          diff-cover coverage.xml --compare-branch origin/${{ github.event.pull_request.base.ref }} --fail-under=80 || true
